### ISSUE TITLE
Wiki: mention `std::thread::yield_now` as an option for yielding from threads

### ISSUE THREAD

**Issue by CenTdemeern1** [rust3ds/ctru-rs#183] opened 2024-04-28 18:47 UTC
# Relevant page: [System Flaws](https://github.com/rust3ds/ctru-rs/wiki/System-Flaws)

In some situations, using `yield_now` may be preferred over `sleep`, which is not mentioned in the relevant paragraph.
That's a shame, because it can be really really useful if you know about it, especially because co-operative threading seems to be its intended purpose.
Instead, the paragraph makes it sound like `sleep` is the only option for something like this, which stopped me from researching this further until today.

# Suggested edit:
> For cooperative threads using `std`, this is done via [`std::thread::sleep`](https://doc.rust-lang.org/std/thread/fn.sleep.html) or via internal waits in functions like [`Mutex::lock`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.lock).

Becomes:
> For cooperative threads using `std`, this is done via [`std::thread::sleep`](https://doc.rust-lang.org/std/thread/fn.sleep.html), [`std::thread::yield_now`](https://doc.rust-lang.org/std/thread/fn.yield_now.html), or via internal waits in functions like [`Mutex::lock`](https://doc.rust-lang.org/std/sync/struct.Mutex.html#method.lock).

# Why is this an issue and not a pull request?
Unfortunately, [GitHub doesn't support making pull requests on Wikis](https://stackoverflow.com/questions/10642928/how-can-i-make-a-pull-request-for-a-wiki-page-on-github).
If I could make a pull request, make an edit suggestion some other way, or edit the wiki directly, I would've preferred that, but alas.

**Comment by Meziu** [comment] 2024-04-28 19:42
That's true, and in the first revision of that Wiki I wanted to add that in as an option, since it always seemed to be glossed over when talking about threading. However, there are some reasons why I decided against adding it.

The default implementation within `std` for `std::thread::yield_now()` uses `sched_yield` [here](https://github.com/rust-lang/rust/blob/ce609db948f210807f61da999c57bd4ae5216254/library/std/src/sys/pal/unix/thread.rs#L115). `sched_yield` is the `pthread` function to handle this sort of thing. The problem is pretty clear when looking at the implementation `devkitARM` uses for this function: [sched_yield (void)](https://github.com/devkitPro/newlib/blob/b539470a8e3be711a1cda852be54e737bbc3795e/libgloss/libsysbase/pthread.c#L1072).

...nothing. It's unimplemented. Which was honestly pretty weird when I looked at it back in the day.

During my research, I came to the understanding that there was no mention of a way for threads to be yielded at will in Horizon OS. As explained [here](https://www.3dbrew.org/wiki/Multi-threading#Threads), the threads with the highest priority will always run to completion first when available, which means that yielding has no effect if no "lower priority" thread exists. It also has no effect if an "higher priority" thread is available, since that would be run regardless. That effectively means that the only case in which such an action would be useful is when multiple threads with the same priority are running concurrently, for which you may want to switch from one to the other. That's probably not the most important feature for such a scheduler (or for a user which is programming for the platform) since most of the concurrent code should be written by keeping in mind the associated `sched priority`, and not with the hope that yielding the thread will run what you actually want.

`3dbrew` [does mention](https://www.3dbrew.org/wiki/KThread) a "dynamic priority" value (which is usually the "queue" index assigned to the thread in `SCHED_FIFO`) but it's unclear whether it's possible to modify it during runtime.

Either way, back then I wasn't deterred from trying to make `yield` work, so I implemented `sched_yield` in `pthread_3ds` myself [here](https://github.com/rust3ds/pthread-3ds/blob/c885d8cda6d0c5b429b5db3a2408bf204fc1097e/src/misc.rs#L4). This uses [`svcThreadSleep`](https://libctru.devkitpro.org/svc_8h.html#ae1fad9317c81076e1394a376ab27c720) as an *hopeful* replacement, since it has actually never been tested. As the docs for that function say, the number of milliseconds specified is the "minimum" amount of time spent waiting, so I'm unsure whether the scheduler even takes into consideration `0` as a parameter (0 was chosen as that's a working replacement for many other operating systems).

If during testing you come to the realization that `yield_now` is actually working (or could work by changing the code in `pthread-3ds`) I will consider adding it in the wiki :+1:.

**Comment by CenTdemeern1** [comment] 2024-04-28 20:15
> If during testing you come to the realization that yield_now is actually working (or could work by changing the code in pthread-3ds) I will consider adding it in the wiki 👍.

Before making this issue I did actually test `yield_now` to make sure it actually worked. From my testing, it did!
I'll quickly push my testing code into a branch (I used an existing test app I made for this) so you can test it and see it in action yourself.

**Comment by CenTdemeern1** [comment] 2024-04-28 20:30
Update: After doing some more testing, it does indeed work, but it's not entirely stable (crashes when you _return_ from the home menu?)
Here is that branch I mentioned, be sure to read the code comments I added: https://github.com/CenTdemeern1/aris-3ds/tree/yield_now

**Comment by Meziu** [comment] 2024-04-29 10:43
> Update: After doing some more testing, it does indeed work, but it's not entirely stable (crashes when you _return_ from the home menu?)

Without considering the crashes (and the fact that what you showed isn't really a minimal test 😅), there might be some issues with the use of `gfx.wait_for_vblank`, since that would give time to the audio code to run either way. I need something a bit more concise than that, that doesn't really get into other thread-related code.

**Comment by CenTdemeern1** [comment] 2024-04-30 02:54
> and the fact that what you showed isn't really a minimal test 😅

I don't exactly recall any mention of me needing to make a minimal example/test/repro, I just worked with what I had

> there might be some issues with the use of `gfx.wait_for_vblank`, since that would give time to the audio code to run either way. I need something a bit more concise than that, that doesn't really get into other thread-related code.

Got it. I'll see what I can do when I have the time.
The main problem with making a minimal example for this kind of thing is proving that it's actually working (which I could do more easily with the audio code I knew would have very clearly visible issues if it didn't work) so I have to think up a solution for that.

**Comment by Meziu** [comment] 2024-05-04 12:21
Actually, it seems to work in a very pretty way. Here's my example:
```rust
use ctru::prelude::*;

fn main() {
    let gfx = Gfx::new().expect("Couldn't obtain GFX controller");
    let mut hid = Hid::new().expect("Couldn't obtain HID controller");
    let apt = Apt::new().expect("Couldn't obtain APT controller");
    let _console = Console::new(gfx.top_screen.borrow_mut());

    std::thread::spawn(|| {
        println!("I'm in the new thread!");
        loop {
            // Comment out this line too see the change in behaviour.
            std::thread::yield_now();
        }
    });

    // We sleep the main thread for a moment since (for SCHED_FIFO) it would run before the new thread otherwise.
    std::thread::sleep(std::time::Duration::from_nanos(1));

    // Without yielding, this point will never be reached.
    println!("I'm in the main thread!");

    println!("\x1b[29;16HPress Start to exit");

    while apt.main_loop() {
        hid.scan_input();

        if hid.keys_down().contains(KeyPad::START) {
            break;
        }

        gfx.wait_for_vblank();
    }
}
```

I'll add it to the wiki, I'm convinced now :+1:

**Closed as completed by Meziu** 2024-05-04 12:21 UTC
